### ISSUE TITLE
Repo has untracked source files: ['klippy/extras/gcode_shell_command.py'

### ISSUE THREAD

**Issue by Heiko910** [Staubgeborener/klipper-backup#17]
First let me say. I appreciate the work that went into this project.
I got it running. I am using the manual backup variant. 
I added the macros to just have the "Update Git" functionality. It reliably pushes backups to my repo on GitHub.
So no problems there but as a result of adding the "gcode_shell_command"  and the macros I now get a info notification in the Mainsail Update Manger next to the "Klipper up to date" which says [Repo has untracked source files: ['klippy/extras/gcode_shell_command.py']

Does anyone have a idea what this means, what is wrong and how it could be fixed?

![Klipper notification](https://github.com/Staubgeborener/klipper-backup/assets/145156088/fd406719-c6c7-435a-8011-ccc37567f59f)

**Comment by Staubgeborener** [comment]
This issue is not related to this project, the [G-Code Shell Command Extension](https://github.com/dw-0/kiauh/blob/master/docs/gcode_shell_command.md) is part of [KIAUH](https://github.com/dw-0/kiauh), so I would suggest opening an issue there or in the official [Mainsail](https://github.com/mainsail-crew) repo.

(But short google search: Seems to be a known issue [here](https://www.reddit.com/r/klippers/comments/158hqxu/repo_has_untracked_source_files/) and [here](https://github.com/mainsail-crew/moonraker-timelapse/issues/128).

**Comment by Heiko910** [comment]
thanks
