### ISSUE TITLE
Question regarding configuration (v1.0.0)

### ISSUE THREAD

**Issue by DrFate09** [Staubgeborener/klipper-backup#28]
Hello and thanks for creating this plugin!

I am a confused by the ".env.example" file. There is an example of "backup_folder=config_backup/klipper" that is supposedly used to back up a folder. In the Wiki under "Installation: Configuration", you mention "All files defined here....must start with path_ followed by the path". There is no mention of using backup_ in the Wiki. Is this a valid command for v1.0.0 or should we just use path_? If we can use backup_, can you add that documentation also to the Wiki?

Thinking about it more...is this the path that you use to sync the files to GitHub? If you could explain this inline as comment in the .env what the purpose of this path is and if we can edit or not, that would be nice.

I am also confused by this:
path_klipperdata=printer_data/config/*
#path_macroscfg=printer_data/macros/*
path_singlefile=printer_data/config/singlefile.cfg

What is the context of using either klipperdata, macroscfg or singlefile after path_? Can we make those whatever we want? What do they correspond to? Do they set up folders that then sync to GitHub for organization?  Some elaboration would be appreciated :)

**Comment by Staubgeborener** [comment]
> There is no mention of using backup_ in the Wiki. Is this a valid command for v1.0.0 or should we just use path_? If we can use backup_, can you add that documentation also to the Wiki?

The backup folder is an exception indeed. The syntax for the backup folder is `backup_folder=config_backup/klipper` or `backup_folder=whatever/iwant`. It doesn't matter because the folder is deleted after the script is executed anyway. However, all other folders must actually be labeled with `path_`. I might add this to the wiki.

> is this the path that you use to sync the files to GitHub?

Yes.

> What is the context of using either klipperdata, macroscfg or singlefile after path_? Can we make those whatever we want?

Yes. The name doesn't matter, it's just for your own orientation. As an extremely abstruse but understandable example:
```
path_theseareallmyfilesinthisfolder=printer_data/config/*
path_ohwaitiforgthisonenevermind=printer_data/config/singlefile.cfg
```
will also work, as those begin with `path_`.

If you have any further questions, feel free to ask. Alternatively, you can simply close this issue once everything has been clarified.
