### ISSUE TITLE
"Klipper-backup is not up to date" Message when running from Mainsail

### ISSUE THREAD

**Issue by zer010gic** [Staubgeborener/klipper-backup#32]
When I run the macro to execute the Klipper-backup script from Mainsail I am getting a message that Klipper-backup is not up to date.  However if I run the script from the terminal it states that it is up to date.  I am also using Mainsail update manager to update the script and I am currently running 1.1.0-0-g713d4cfe.

<img width="556" alt="Screenshot 2024-01-18 at 8 18 36 PM" src="https://github.com/Staubgeborener/klipper-backup/assets/73259984/59591dbf-3f09-410c-ab40-b6245a5feb10">
<img width="554" alt="Screenshot 2024-01-18 at 8 18 24 PM" src="https://github.com/Staubgeborener/klipper-backup/assets/73259984/d63fe5ab-aed3-44c5-a76b-0d300c610c9e">
<img width="829" alt="Screenshot 2024-01-18 at 8 18 02 PM" src="https://github.com/Staubgeborener/klipper-backup/assets/73259984/13278f37-9aa7-4029-8490-0466df1db1b3">

**Comment by Staubgeborener** [comment]
Thanks. The problem here is that when running in mainsail, things like `git ls-remote` can't work at all, because you have to be in the klipper-backup directory at that time. The same error message can be achieved by running something like `./klipper-backup/script.sh` in the `$home` directory.

Long story short: Ignore this message for now.

Since I cannot find an elegant way to fix this, I will simply remove the corresponding line completely in the next time.  Maybe I start again with something like a `version` file to check this, like I did a couple of weeks ago.

**Comment by Staubgeborener** [comment]
I think i found a good solution with `git -C [...]`, could you please test this with the mainsail ui?

**Comment by zer010gic** [comment]
The latest update fixed it.
