### ISSUE TITLE
Missing instruction for copying .env.example to .env

### ISSUE THREAD

**Issue by MallocArray** [Staubgeborener/klipper-backup#5]
When following the Wiki, this is the first page that I saw it talk about the .env file
https://github.com/Staubgeborener/klipper-backup/wiki/Configuration

It starts with saying to open the .env file, but at this stage, I believe it exists as .env.example only.  I did `cp .env.example .env` to make a copy and then edited the new .env file

Perhaps this is common knowledge, but I could see it tripping up some users, especially with the file being hidden.

**Comment by Staubgeborener** [comment]
One step before the installation script is executed. It's true, about 3 weeks ago the wiki was wrong at this point and no .env was created because of the folder structure. This has been fixed, as i said [here](https://github.com/Staubgeborener/klipper-backup/issues/4#issuecomment-1590680600). [This](https://github.com/Staubgeborener/klipper-backup/wiki/Installation:-Moonraker-Support/84dc6d773b6eee220e2a6baa01a1e4b55865dc2a) is the wrong installation (3 weeks old right now) and [this](https://github.com/Staubgeborener/klipper-backup/wiki/Installation%3A-Moonraker-Support) is the correct one. But nevertheless, thanks for watching out.
