### ISSUE TITLE
Moonraker update manager issue

### ISSUE THREAD

**Issue by mrodyhin** [Staubgeborener/klipper-backup#7]
It's recommended to use moonraker update manager to update the script, but after first backup is done, update manager  says that the repo is invalid. The fix button moves repo to ok state, but backup would fail after that untill you roll back all backups in backup repo.
<img width="879" alt="image" src="https://github.com/Staubgeborener/klipper-backup/assets/11924548/97c27947-783e-4bcf-99bb-ec3c7ab93dc0">

**Comment by Staubgeborener** [comment]
This is a known issue, if you want help keep an eye [here](https://github.com/Staubgeborener/klipper-backup/issues/6).
TLTR: moonraker notices that something has been changed in the repository (since various files have been deleted by the script and directories may be created by the user) and therefore returns this dirty flag
