### ISSUE TITLE
Split .env file into seperate files for future restore use

### ISSUE THREAD

**Issue by DrFate09** [Staubgeborener/klipper-backup#92]
### Is your feature request related to a problem? Please describe.

I successfully set up the plugin today and it is working great! I did have an idea while I was working on modifying my .env file to include some path includes and excludes....

### Describe the solution you'd like

Could we split the current .env file into two seperate files? 

The first .env would house the "secrets" (aka GitHub token and personal info) and the second .env would include the path includes and excludes. 

If this could be done, we could backup the paths. env file for future restores (if our HDD dies) so we would not need to rebuild it but still keep the "secrets" .env file off of GitHub (so it would not be included in the backup).

### Describe alternatives you've considered

Is this possible (I'm not a developer)?

**Comment by Tylerjet** [comment]
Restore functionality is my next little project plan (Once Staubgeborener and I are done mucking around with the installer script and Kiauh support) just not sure when i will get to it, but likely a part of the process will be creating a config file that is generated by pulling data from the .env instead of splitting them and then using that config file when restoring.
